### PR TITLE
Add `socket.io` to NPM installation instructions

### PR DESCRIPTION
**Pull request by mtodd**
This was a required step for me to get it started.

### CODE REVIEW

**Comment by etiennesegonzac** [comment]
It was a required step for me to.
Happy to see there's already a patch.

**Comment by koraktor** [comment]
socket.io is included as a Git submodule in [`Node/socket.io-node`](https://github.com/mtodd/TermKit/tree/master/Node), so this should get you going (as described in the `README`):

```
git clone git@github.com:unconed/TermKit.git --recursive
```

**Comment by etiennesegonzac** [comment]
Good catch.
I got a git error "error: unknown option `recursive'" when clonning with --recursive, guess that's what happened to @mtodd to.

**Comment by koraktor** [comment]
Oh, `--recursive` is Git >= 1.6.5. Maybe that should be mentioned in the `README` instead.

Here's the equivalent for older Git versions:

```
git clone git@github.com:unconed/TermKit.git
git submodule update --init
```

**Comment by etiennesegonzac** [comment]
Yep, I'm on git version 1.6.3.3.
Your workaround works fine BTW. Thanks !

**Pull request closed without merging**
