### PR TITLE
Submodules path has changed.

### PR DESCRIPTION
**Pull request by Souvent22**
The submodules, in which Termkit is dependent on, their paths have changed.

### CODE REVIEW

**Comment by tovbinm** [comment]
Please pull this, it works just fine

**Comment by miguel-negrao** [comment]
please, pull this, otherwise git cannot clone the submodules...

**Comment by ryansch** [comment]
This still needs to be merged.

**Comment by callumgare** [comment]
Seconded, still waiting.

**Comment by sneilan** [comment]
thirded.

**Comment by alexkrishnan** [comment]
fourthed.

**Comment by jackfranklin** [comment]
This is preventing me installing Termkit - please pull this!

**Comment by bishopandco** [comment]
+1

I changed them all to git:// in my clone and was able to sub mod fine.

**Comment by conatus** [comment]
Please merge, can't install TermKit - think of all my sense of aesthetics!

**Comment by Souvent22** [comment]
Perhaps the maintainer is no longer actively developing this module. This may need to be pulled into another fork and someone else carry the torch.

**Comment by arturadib** [comment]
@unconed ?

**Comment by inspire22** [comment]
arg

**Comment by erain** [comment]
Same problems happened to me. Please pull this.

**Comment by ndbroadbent** [comment]
Hi @unconed, can you please add some more maintainers to this project? We don't mind if you have lost interest, but 13 people have been waiting for 6 months ...

Please add a couple more maintainers to the project, like @callumgare and @Souvent22.

Otherwise, I second the decision to fork this project and work on it somewhere else...

**Comment by karlbohlmark** [comment]
I think it it seems pretty likely that this isn't going anywhere anytime soon.

+1 on forking

**Comment by conatus** [comment]
Seems sad that I never got this to work at all because of this bug. Move to fork as well, if only temporarily to fix these sort of problems.

**Comment by unconed** [comment]
I find it odd that supposedly people are interested, yet literally nobody wants to talk to me about architecture.

**Comment by conatus** [comment]
Thanks very much for this, will be interested to see how this all works.

**Comment by bilke** [comment]
@unconed I just discovered this project and it looks awesome!! After reading your blog I read through the Github page and also the open issues. Your project has over 3000 watchers and 130 forks and it seems to be that many people want to help with this project.

But I am under the impression that this help is not adopted by you. This pull request existed for 5 months before you merged it. And there are many open issues which are not commented by you.

Regarding discussion about this project maybe you can point people to a place where this can happen, maybe a mailing list or a forum...

I really hope that this project will evolve to a new way to interact with the shell!

**Comment by sneilan** [comment]
"I find it odd that supposedly people are interested, yet literally nobody wants to talk to me about architecture."

That's because it doesn't work.

**Comment by unconed** [comment]
No, that's because after months of talk, I realized there is zero added value in doing this in public. TermKit will be done when it's done. Consider this codebase abandoned, have fun with it if you like, but it's out of date.

**Comment by sneilan** [comment]
Ouch. :(

**Comment by boxed** [comment]
@unconed you could try this approach: http://felixge.de/2013/03/11/the-pull-request-hack.html

**Pull request merged**
