### PR TITLE
Updated install instructions since order matters :)

### PR DESCRIPTION
**Pull request by soffes**
I had a really hard time figuring out to install TermKit. Updated the readme so it's easier for others.

### CODE REVIEW

**Comment by ryansch** [comment]
Why did you push the `npm install mime` command after the clone?  You can install npm packages any time after npm is installed and you don't need to be within the TermKit clone to do it.

**Comment by soffes** [comment]
I could only get it to work if I cloned and then did `npm install mime` in the TermKit directory. I know nothing about node though. After spending close to an hour trying to get it to work, this is what finally did it.

**Comment by drudge** [comment]
Unless you specify -g, newer versions of npm will install into $CWD/node_modules.

**Comment by soffes** [comment]
I used the current version of npm at the time without any options.

**Pull request closed without merging**
